### ISSUE TITLE
Warning! Error encountered during contract execution [Bad instruction] 

### ISSUE THREAD

**Issue by jewom** [openanx/OpenANXToken#3]
Hi,

When I try to move my tokens from MyEtherWallet to an exchange (HitBTC), I have this problem : 
Warning! Error encountered during contract execution [Bad instruction] 

What I have to do ?

This is the transaction link : 
https://etherscan.io/tx/0xe9f8a205be3469be57c65b39dd632b066da84cef893d3644f16b4bb710c14e6d

Regards,

**Comment by lionello** [comment]
It looks like you haven't completed the KYC registration on the oax.org website. You can check by invoking the `kycRequired` on the token contract for your address. It returns `true`, meaning that you're still required to complete the KYC.
